project_id = "qxtnpwmdspwidrtiqimv"

[functions.get-revenue]
verify_jwt = false

[functions.get-videos]
verify_jwt = false

[functions.get-daily-revenue]
verify_jwt = false

[functions.get-traffic-source]
verify_jwt = false

[functions.get-country-revenue]
verify_jwt = false

[functions.get-device-revenue]
verify_jwt = false

[functions.get-subscriber-status]
verify_jwt = false

[functions.get-subscriber-count]
verify_jwt = false

[functions.ig-thumbnail-proxy]
verify_jwt = false

[functions.get-video-thumbnail]
verify_jwt = false
